name: gcc

on: push #[push, pull_request]

jobs:

  main:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install ninja-build lld gcc-10 g++-10
          sudo ln -sf /usr/local/bin/ld /usr/bin/lld
      - name: Configure CMake
        run: |
          cmake . -DBUILD_TESTING=ON -B build \
            -G "Ninja"                  \
            -DCMAKE_BUILD_TYPE=Debug    \
            -DCMAKE_C_COMPILER=gcc-10   \
            -DCMAKE_CXX_COMPILER=g++-10 \

      - name: Build
        run:
          cmake --build build

      - name: Test
        run: |
          cd build
          ctest --output-on-failure -C Debug -V
          ctest --output-on-failure -C Release -V